version: "3.9"

services:
    mysql:
        image: mysql:8.0
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        ports:
            - "3306:3306"
    app:
        build: .
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html
        depends_on:
            - mysql
